In [27]:
import pandas as pd

In [28]:
dataset = pd.read_csv("DLTINS_20210117_01of01.csv")

C:\Users\ram\AppData\Local\Temp\ipykernel_6256\2969708780.py:1: DtypeWarning: Columns (12,15,18,19,21,22,24,26,27,28,29,32,41,44,45,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,83,84,85,86,87,90,91,93,94,95,96,97,98,99,100,101,102,103,104,105,107,108,110,112,113,114,115,118,119,120,121,122,123,124,125,126,128,129,131,132,133,134,135,136,137,139,140,141,142,143,144,145,146,147,148,149,150,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,169,170,172,174,175,176,177,178,179,181,182,183,184,185) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("DLTINS_20210117_01of01.csv")

In [29]:
dataset.head()

,ns2:Id = ns3:NtlCmptntAuthrty,ns2:Id2,ns2:BizMsgIdr,ns2:MsgDefIdr,ns2:CreDt,ns3:NtlCmptntAuthrty,ns3:Dt,ns3:Id,ns3:FullNm,ns3:ShrtNm,...,ns3:Nm126,ns3:ISIN127,ns3:OptnTp128,ns3:Amt129,Ccy130,ns3:Pdg131,ns3:OptnExrcStyle132,ns3:DlvryTp133,ns3:OthrNtnlCcy134,ns3:PricMltplr135
0,EU,Public,DLTINS_20210117_01of01,auth.036.001.02,2021-01-17T01:17:07.027Z,EU,17-01-21,DE000A1R07V3,Kreditanst.f.Wiederaufbau Anl.v.2014 (2021),KFW/1.625 ANL 20210115 GGAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EU,Public,DLTINS_20210117_01of01,auth.036.001.02,2021-01-17T01:17:07.027Z,EU,17-01-21,DE000A1R07V3,KFW 1 5/8 01/15/21,KFW/1.625 ANL 20210115 GGAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EU,Public,DLTINS_20210117_01of01,auth.036.001.02,2021-01-17T01:17:07.027Z,EU,17-01-21,DE000A1R07V3,Kreditanst.f.Wiederaufbau Anl.v.2014 (2021),KFW/1.625 ANL 20210115 GGAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EU,Public,DLTINS_20210117_01of01,auth.036.001.02,2021-01-17T01:17:07.027Z,EU,17-01-21,DE000A1R07V3,Kreditanst.f.Wiederaufbau Anl.v.2014 (2021),KFW/1.625 ANL 20210115 GGAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EU,Public,DLTINS_20210117_01of01,auth.036.001.02,2021-01-17T01:17:07.027Z,EU,17-01-21,DE000A1X3J56,IKB Deutsche Industriebank AG Stufenz.MTN-IHS ...,IKB DT.INDRIEBK/VAR MTI 20210120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
columns_name = (list) (dataset.columns)

In [31]:
columns_name

['ns2:Id = ns3:NtlCmptntAuthrty',
 'ns2:Id2',
 'ns2:BizMsgIdr',
 'ns2:MsgDefIdr',
 'ns2:CreDt',
 'ns3:NtlCmptntAuthrty',
 'ns3:Dt',
 'ns3:Id',
 'ns3:FullNm',
 'ns3:ShrtNm',
 'ns3:ClssfctnTp',
 'ns3:NtnlCcy',
 'ns3:CmmdtyDerivInd',
 'ns3:Issr',
 'ns3:Id3',
 'ns3:IssrReq',
 'ns3:FrstTradDt',
 'ns3:TermntnDt',
 'ns3:AdmssnApprvlDtByIssr',
 'ns3:ReqForAdmssnDt',
 'ns3:TtlIssdNmnlAmt',
 'Ccy',
 'ns3:MtrtyDt',
 'ns3:NmnlValPerUnit',
 'Ccy4',
 'ns3:Fxd',
 'ns3:ISIN',
 'ns3:Indx',
 'ns3:Nm',
 'ns3:Unit',
 'ns3:Val',
 'ns3:BsisPtSprd',
 'ns3:DebtSnrty',
 'ns3:RlvntCmptntAuthrty',
 'ns3:RlvntTradgVn',
 'ns3:FrDt',
 'ns3:ToDt',
 'ns3:PricMltplr',
 'ns3:OptnTp',
 'ns3:Amt',
 'Ccy5',
 'ns3:Sgn',
 'ns3:BsisPts',
 'ns3:Pctg',
 'ns3:Pdg',
 'ns3:Ccy',
 'ns3:OptnExrcStyle',
 'ns3:DlvryTp',
 'ns3:FxTp',
 'ns3:OthrNtnlCcy',
 'ns3:BasePdct',
 'ns3:SubPdct',
 'ns3:AddtlSubPdct',
 'ns3:BasePdct6',
 'ns3:SubPdct7',
 'ns3:AddtlSubPdct8',
 'ns3:BasePdct9',
 'ns3:SubPdct10',
 'ns3:AddtlSubPdct11',
 'ns3:BasePdct12',
 'ns3:SubPdct13',
 'ns3:AddtlSubPdct14',
 'ns3:BasePdct15',
 'ns3:SubPdct16',
 'ns3:AddtlSubPdct17',
 'ns3:BasePdct18',
 'ns3:SubPdct19',
 'ns3:BasePdct20',
 'ns3:SubPdct21',
 'ns3:AddtlSubPdct22',
 'ns3:BasePdct23',
 'ns3:BasePdct24',
 'ns3:SubPdct25',
 'ns3:AddtlSubPdct26',
 'ns3:BasePdct27',
 'ns3:SubPdct28',
 'ns3:BasePdct29',
 'ns3:TxTp',
 'ns3:FnlPricTp',
 'ns3:Nm30',
 'ns3:Indx31',
 'ns3:Unit32',
 'ns3:Val33',
 'ns3:OthrNtnlCcy34',
 'ns3:ISIN35',
 'ns3:Nm36',
 'ns3:Indx37',
 'ns3:Unit38',
 'ns3:Val39',
 'ns3:ISIN40',
 'ns3:LEI',
 'ns3:ISIN41',
 'ns3:XpryDt',
 'ns3:Id42',
 'ns3:FullNm43',
 'ns3:ShrtNm44',
 'ns3:ClssfctnTp45',
 'ns3:NtnlCcy46',
 'ns3:CmmdtyDerivInd47',
 'ns3:Issr48',
 'ns3:Id49',
 'ns3:IssrReq50',
 'ns3:FrstTradDt51',
 'ns3:TermntnDt52',
 'ns3:AdmssnApprvlDtByIssr53',
 'ns3:ReqForAdmssnDt54',
 'ns3:TtlIssdNmnlAmt55',
 'Ccy56',
 'ns3:MtrtyDt57',
 'ns3:NmnlValPerUnit58',
 'Ccy59',
 'ns3:Fxd60',
 'ns3:ISIN61',
 'ns3:Indx62',
 'ns3:Nm63',
 'ns3:Unit64',
 'ns3:Val65',
 'ns3:BsisPtSprd66',
 'ns3:DebtSnrty67',
 'ns3:RlvntCmptntAuthrty68',
 'ns3:FrDt69',
 'ns3:RlvntTradgVn70',
 'ns3:ISIN71',
 'ns3:ISIN72',
 'ns3:Nm73',
 'ns3:DlvryTp74',
 'ns3:OptnTp75',
 'ns3:Amt76',
 'Ccy77',
 'ns3:Sgn78',
 'ns3:BsisPts79',
 'ns3:Pdg80',
 'ns3:OptnExrcStyle81',
 'ns3:XpryDt82',
 'ns3:OthrNtnlCcy83',
 'ns3:FxTp84',
 'ns3:Indx85',
 'ns3:Unit86',
 'ns3:Val87',
 'ns3:BasePdct88',
 'ns3:SubPdct89',
 'ns3:AddtlSubPdct90',
 'ns3:BasePdct91',
 'ns3:SubPdct92',
 'ns3:AddtlSubPdct93',
 'ns3:BasePdct94',
 'ns3:SubPdct95',
 'ns3:AddtlSubPdct96',
 'ns3:BasePdct97',
 'ns3:SubPdct98',
 'ns3:AddtlSubPdct99',
 'ns3:PricMltplr100',
 'ns3:Id101',
 'ns3:FullNm102',
 'ns3:ShrtNm103',
 'ns3:ClssfctnTp104',
 'ns3:NtnlCcy105',
 'ns3:CmmdtyDerivInd106',
 'ns3:Issr107',
 'ns3:Id108',
 'ns3:IssrReq109',
 'ns3:AdmssnApprvlDtByIssr110',
 'ns3:ReqForAdmssnDt111',
 'ns3:FrstTradDt112',
 'ns3:TermntnDt113',
 'ns3:RlvntCmptntAuthrty114',
 'ns3:FrDt115',
 'ns3:RlvntTradgVn116',
 'ns3:TtlIssdNmnlAmt117',
 'Ccy118',
 'ns3:MtrtyDt119',
 'ns3:NmnlValPerUnit120',
 'Ccy121',
 'ns3:Fxd122',
 'ns3:DebtSnrty123',
 'ns3:XpryDt124',
 'ns3:ISIN125',
 'ns3:Nm126',
 'ns3:ISIN127',
 'ns3:OptnTp128',
 'ns3:Amt129',
 'Ccy130',
 'ns3:Pdg131',
 'ns3:OptnExrcStyle132',
 'ns3:DlvryTp133',
 'ns3:OthrNtnlCcy134',
 'ns3:PricMltplr135']

In [32]:
dataset.isnull().sum()

ns2:Id = ns3:NtlCmptntAuthrty         0
ns2:Id2                               0
ns2:BizMsgIdr                         0
ns2:MsgDefIdr                         0
ns2:CreDt                             0
                                  ...
ns3:Pdg131                       141821
ns3:OptnExrcStyle132             140722
ns3:DlvryTp133                   140672
ns3:OthrNtnlCcy134               141804
ns3:PricMltplr135                141783
Length: 187, dtype: int64

In [33]:
dataset.shape

(141822, 187)

In [34]:
# stroing the columns to delete from dataset that are containing null values more than 100000
null_columns = [feature for feature in dataset.columns if dataset[feature].isnull().sum() > 100000]

In [35]:
len(null_columns)

157

In [36]:
data_set = dataset.drop(null_columns, axis = 1)

In [37]:
data_set.shape

(141822, 30)

In [38]:
features_with_null_values = [feature for feature in data_set.columns if data_set[feature].isnull().sum() > 0]

In [39]:
len(features_with_null_values)

23

In [40]:
data_set[features_with_null_values].isnull().sum()

ns3:Id                    39735
ns3:FullNm                39735
ns3:ShrtNm                39735
ns3:ClssfctnTp            39735
ns3:NtnlCcy               39735
ns3:CmmdtyDerivInd        39735
ns3:Issr                  39735
ns3:Id3                   39735
ns3:IssrReq               39735
ns3:FrstTradDt            39735
ns3:TermntnDt             39735
ns3:RlvntCmptntAuthrty    39735
ns3:RlvntTradgVn          39735
ns3:FrDt                  52462
ns3:ToDt                  52462
ns3:PricMltplr            53698
ns3:OptnTp                51854
ns3:Amt                   62895
Ccy5                      62895
ns3:OptnExrcStyle         51883
ns3:DlvryTp               45209
ns3:ISIN40                61153
ns3:XpryDt                47361
dtype: int64

In [41]:
numerical_features = [feature for feature in features_with_null_values if data_set[feature].dtype != "O"]
numerical_features

['ns3:PricMltplr', 'ns3:Amt']

In [43]:
# to remove the null values from the numerical features
for feature in numerical_features:
    median = data_set[feature].median()
    data_set[feature] = data_set[feature].fillna(median)

In [45]:
data_set[numerical_features].isnull().sum()

ns3:PricMltplr    0
ns3:Amt           0
dtype: int64

In [73]:
data_set[numerical_features[0]].unique()

array([1.0000000e+02, 1.0000000e+00, 1.0000000e-02, 1.0000000e-01,
       3.3156000e+01, 4.7303000e+01, 1.4492700e+02, 1.0000000e+01,
       1.0100000e+02, 1.0500000e+02, 1.6000000e+02, 1.6800000e+02,
       6.0000000e+01, 1.2000000e+02, 4.8000000e+01, 5.0000000e+01,
       2.0000000e+01, 5.0000000e+00, 2.0000000e+00, 1.0800000e+02,
       2.4000000e+01, 1.2000000e+01, 1.0000000e+03, 4.0000000e+00,
       6.0000000e+00, 1.4000000e+02, 3.3600000e+02, 3.0000000e+00,
       1.8000000e+01, 1.4410000e+03, 1.0000000e+04, 2.0000000e+02,
       1.0000000e-04, 4.0000000e+02, 5.0000000e+02, 5.0000000e+03,
       5.7200000e+02, 2.5000000e+03, 1.6000000e+03, 8.0000000e+02,
       8.0000000e+03, 3.1200000e+02, 1.0403000e-01, 3.5415250e+03,
       3.0300000e-01, 1.5000000e+00, 1.0200000e+02, 1.0300000e+02,
       1.0700000e+02, 1.5100000e+02, 1.1000000e+02, 1.0000000e-03,
       5.0000000e-02, 6.2766000e+01, 4.0000000e-01, 5.0000000e-01,
       2.8600000e-01, 2.8000000e-02, 2.8300000e-01, 2.9200000e-01,
       5.8910000e+00, 5.5400000e-01, 4.6200000e-01, 3.9600000e-01,
       3.4600000e-01, 5.8550000e+00, 2.7600000e-01, 8.5820000e+00,
       4.2800000e-01, 5.5100000e-01, 8.8440000e+00, 2.6300000e-01,
       3.0800000e-01, 8.3333000e+01, 6.6666000e+01, 7.1428000e+01,
       1.5920000e+00, 9.0909000e+01, 7.6923000e+01, 5.5555000e+01,
       5.2631000e+01, 5.1282000e+01, 5.7142000e+01, 5.4054000e+01,
       5.8823000e+01, 6.2500000e+01, 4.3360000e+01, 4.1220000e+01,
       2.2363000e+01, 6.4913000e+01, 1.2269000e+01, 1.5840000e+00,
       5.0000000e-03, 4.4870000e+00, 6.9200000e-01, 1.3440000e+00,
       4.2970000e+00, 5.3100000e-01, 4.2000000e-02, 1.1513000e+01,
       7.6750000e+00, 1.7670000e+00, 1.4560000e+00, 7.6900000e-01,
       2.0410000e+00, 6.7500000e-01, 5.1720000e+00, 9.4000000e-02,
       9.2800000e-01, 1.3070000e+00, 1.7850000e+00, 1.1370000e+00,
       2.6190000e+00, 5.0900000e-01, 3.8167000e+01, 7.7890000e+00,
       2.4410000e+00, 2.3200000e+00, 1.5980000e+00, 5.0300000e-01,
       4.3100000e-01, 1.8740000e+00, 3.7900000e-01, 7.7150000e+00,
       6.8100000e-01, 5.1200000e-01, 8.8600000e-01, 2.9530000e+00,
       2.5310000e+00, 1.4760000e+00, 1.2350000e+00, 2.6110000e+00,
       7.4000000e-01, 1.9000000e-02, 4.3000000e-01, 6.7000000e-02,
       4.5000000e-02, 1.7200000e-01, 2.4390000e+00, 5.0320000e+00,
       1.1360000e+00, 5.6390000e+00, 7.4000000e-02, 3.6090000e+00,
       3.6890000e+00, 5.3530000e+00, 6.6100000e-01, 1.7920000e+00,
       3.7700000e+00, 1.1520000e+00, 9.8700000e-01, 2.1360000e+00,
       9.0700000e-01, 1.7020000e+00, 1.6560000e+00, 6.5900000e-01,
       2.2379000e+01, 1.4950000e+00, 1.4490000e+00, 3.9070000e+00,
       6.8000000e-01, 1.0430000e+00, 1.0490000e+00, 7.0400000e-01,
       1.9200000e-01, 5.7800000e-01, 1.0130000e+00, 3.3770000e+00,
       8.6800000e-01, 2.8940000e+00, 1.9290000e+00, 1.4093000e+01,
       1.0427000e+01, 9.6600000e-01, 5.5200000e-01, 6.7380000e+00,
       2.2350000e+00, 1.9160000e+00, 7.8000000e-02, 2.6250000e+00,
       4.6050000e+00, 3.6830000e+00, 1.1764000e+01, 2.0110000e+00,
       3.5200000e+00, 1.7600000e+00, 6.1650000e+00, 1.9000000e+01,
       9.0000000e-03, 5.1360000e+00, 4.3900000e-01, 1.4650000e+00,
       2.5640000e+00, 2.1970000e+00, 1.1466000e+01, 2.2732000e+01,
       1.9330000e+00, 2.0990000e+00, 1.2110000e+00, 4.0000000e-03,
       1.2940000e+00, 4.3130000e+00, 1.2070000e+00, 4.0260000e+00,
       3.4510000e+00, 9.0900000e-01, 3.8600000e-01, 3.9300000e-01,
       1.1030000e+00, 6.2110000e+00, 1.7950000e+00, 8.7500000e-01,
       3.8550000e+00, 3.3050000e+00, 4.8300000e-01, 2.5500000e+01,
       5.2000000e-01, 4.0960000e+00, 3.4130000e+00, 3.9590000e+00,
       1.3080000e+00, 9.6210000e+00, 5.3620000e+00, 4.6920000e+00,
       5.4760000e+00, 9.4900000e-01, 2.8340000e+00, 4.9600000e+00,
       3.3270000e+00, 1.7140000e+00, 4.0442000e+01, 1.0514000e+01,
       2.2320000e+00, 1.1990000e+00, 1.0760000e+00, 1.0810000e+00,
       1.5250000e+00, 4.0060000e+00, 2.1570000e+00, 5.9000000e-01,
       1.9690000e+00, 1.6410000e+00, 9.8500000e-01, 1.6880000e+00,
       2.3230000e+00, 2.0370000e+00, 7.7450000e+00, 7.2500000e-01,
       1.4450000e+00, 7.5800000e-01, 5.0500000e-01, 3.3980000e+00,
       1.4640000e+00, 6.8600000e-01, 9.4370000e+00, 6.2910000e+00,
       1.7500000e-01, 7.7300000e-01, 6.3240000e+00, 1.0909000e+01,
       8.6400000e-01, 7.3000000e-01, 7.5280000e+00, 1.1000000e-02,
       1.1430000e+00, 7.0300000e-01, 4.7300000e-01, 4.3700000e-01,
       3.8900000e-01, 2.3610000e+00, 2.2200000e-01, 2.8200000e-01,
       1.3570000e+00, 1.1960000e+00, 3.2520000e+00, 1.3553000e+01,
       1.1350000e+00, 4.3010000e+00, 9.3900000e-01, 2.0240000e+00,
       2.9780000e+00, 1.8940000e+00, 4.8000000e-02, 1.4400000e-01,
       6.2400000e-01, 4.0000000e-02, 1.3240000e+00, 8.7979000e+01,
       1.0950000e+00, 4.4530000e+00, 7.1200000e-01, 2.1846000e+01,
       2.7950000e+00, 2.5100000e-01, 1.8690000e+00, 8.5920000e+00,
       1.3580000e+00, 1.1042000e+01, 1.0900000e-01, 7.1800000e-01,
       8.8000000e-01, 6.3610000e+00, 5.8200000e-01, 1.3377000e+01,
       1.9710000e+00, 1.1510000e+00, 2.3340000e+00, 2.8600000e+00,
       9.4710000e+00, 5.5240000e+00, 3.8100000e-01, 1.2252000e+01,
       1.8179000e+01, 3.2300000e+00, 2.1500000e-01, 6.4600000e-01,
       2.1530000e+00, 6.6060000e+00, 3.6080000e+00, 1.0390000e+00,
       6.9610000e+00, 2.0950000e+00, 1.2380000e+00, 4.5040000e+00,
       9.6200000e-01, 2.7230000e+00, 8.0930000e+00, 4.5800000e-01,
       1.5290000e+00, 1.2240000e+00, 1.1000000e+00, 7.3300000e-01,
       6.1000000e-01, 1.0060000e+00, 4.9000000e-01, 1.1860000e+00,
       7.9100000e-01, 8.4430000e+00, 2.5250000e+00, 1.3574000e+01,
       6.3000000e-02, 1.0010000e+00, 1.1287000e+01, 3.8820000e+00,
       8.7970000e+00, 8.9300000e-01, 1.6770000e+00, 3.7000000e-01,
       2.2780000e+00, 7.0950000e+00, 1.5713000e+01, 2.2020000e+00,
       4.4000000e-01, 4.9880000e+00, 8.4800000e-01, 3.8010000e+00,
       1.9080000e+00, 9.2860000e+00, 7.0530000e+00, 6.3890000e+00,
       8.3300000e-01, 2.9980000e+00, 1.7310000e+00, 1.8500000e-01,
       5.5600000e-01, 1.8550000e+00, 3.8080000e+00, 1.0450000e+00,
       7.7500000e-01, 1.1440000e+00, 2.5500000e-01, 1.4200000e+00,
       1.7300000e-01, 3.4700000e-01, 1.1590000e+00, 1.3900000e-01,
       1.7100000e-01, 7.4300000e-01, 1.6856000e+01, 4.0400000e-01,
       7.2700000e-01, 0.0000000e+00, 7.7399000e+01, 3.4352000e+01,
       7.6149000e+01, 1.5921940e+02, 6.7309300e+01, 5.5747800e+02,
       1.4200000e-01, 5.4300000e-01, 1.1250000e+00, 5.3800000e-01,
       1.8350000e+00, 1.2000000e-01, 5.8000000e-02, 8.6200000e-01,
       1.1000000e-01, 3.1230000e+00, 2.5700000e-01, 7.2800000e-01,
       4.8400000e-01, 3.5700000e-01, 3.2000000e-01, 6.2100000e-01,
       1.0700000e-01, 2.5900000e-01, 5.4000000e-02, 2.2900000e-01,
       1.1400000e-01, 7.5000000e-01, 3.9000000e-02, 3.0000000e-03,
       1.9300000e-01, 1.3300000e-01, 3.5300000e-01, 6.9880000e+00,
       2.7000000e-02, 1.2000000e-02, 1.4700000e-01, 2.4500000e-01,
       7.3700000e-01, 3.8700000e-01, 1.1610000e+00, 7.0000000e-02,
       1.1800000e+00, 1.0260000e+00, 2.4000000e-02, 1.1650000e+00,
       8.3000000e-02, 9.4700000e-01, 7.2000000e-02, 4.0900000e-01,
       5.1000000e-01, 4.1000000e-01, 2.7000000e-01, 1.8530000e+00,
       1.6150000e+00, 5.7400000e-01, 2.7700000e-01, 1.3000000e+00,
       5.3500000e-01, 1.6050000e+00, 5.3520000e+00, 8.6290000e+00,
       2.7100000e-01, 9.6100000e-01, 7.2000000e-01, 1.0780000e+00,
       2.5000000e-01, 7.1000000e-02, 2.1400000e-01, 7.1400000e-01,
       4.1000000e-02, 1.2500000e-01, 4.1600000e-01, 7.2300000e-01,
       1.9110000e+00, 3.3500000e-01, 1.5730000e+00, 6.4100000e-01,
       2.8000000e-01, 2.8270000e+00, 5.2695000e+01, 5.4310000e+00,
       2.0140000e+00, 9.4500000e-01, 9.0100000e-01, 2.5990000e+00,
       1.9550000e+00, 1.7900000e-01, 1.0620000e+00, 8.9520000e+00,
       3.9480000e+00, 1.8090000e+00, 9.8430000e+00, 1.8600000e-01,
       2.1000000e+00, 1.4000000e+00, 1.5690000e+00, 5.3900000e-01,
       6.9370000e+00, 3.3810000e+00, 6.7600000e-01, 2.2540000e+00,
       3.9440000e+00, 1.9700000e-01, 1.2750000e+00, 8.5000000e-01,
       8.9200000e-01, 5.9500000e-01, 2.6510000e+00, 1.0990000e+00,
       2.2090000e+00, 7.8700000e-01, 2.9260000e+00, 2.0980000e+00,
       1.7980000e+00, 3.4707000e+01, 7.6100000e-01, 2.4200000e-01,
       6.3400000e-01, 4.2200000e-01, 1.5200000e+00, 1.0090000e+00,
       2.0870000e+00, 1.7510000e+01, 2.3240000e+00, 1.3127000e+01,
       8.7510000e+00, 3.4800000e-01, 4.5500000e-01, 2.0710000e+00,
       1.3760000e+00, 4.3330000e+00, 2.4710000e+00, 8.4000000e-02,
       2.4700000e-01, 1.8710000e+00, 1.5590000e+00, 1.0207000e+01,
       4.6800000e-01, 1.5880000e+00, 1.4900000e-01, 1.1880000e+00,
       2.5485000e+01, 3.7080000e+00, 3.1700000e-01, 9.5300000e-01,
       3.1790000e+00, 6.3500000e-01, 2.1190000e+00, 6.6600000e-01,
       4.4400000e-01, 1.7490000e+00, 1.4420000e+00, 2.8570000e+00,
       3.6000000e-02, 3.6100000e-01, 1.0080000e+00, 2.2030000e+00,
       1.2660000e+00, 1.2800000e+00, 2.1800000e-01, 1.6860000e+00,
       1.6310000e+00, 2.1100000e-01, 7.0500000e-01, 1.3860000e+00,
       7.9200000e-01, 8.9000000e-01, 2.8230000e+00, 2.6260000e+00,
       2.2510000e+00, 3.4790000e+00, 1.5090000e+00, 1.2590000e+00,
       6.7178000e+01, 2.4260000e+00, 2.0000000e+03, 1.0057310e+02,
       1.0784520e+02, 1.0020350e+02, 2.9140225e+03, 3.6243230e+02])

In [46]:
# removing the null values from the categorical features
categorical_features = [feature for feature in features_with_null_values if data_set[feature].dtype == "O"]
len(categorical_features)

21

In [47]:
for feature in categorical_features:
    data_set[feature] = data_set[feature].fillna("Missing")

In [48]:
data_set[categorical_features].isnull().sum()

ns3:Id                    0
ns3:FullNm                0
ns3:ShrtNm                0
ns3:ClssfctnTp            0
ns3:NtnlCcy               0
ns3:CmmdtyDerivInd        0
ns3:Issr                  0
ns3:Id3                   0
ns3:IssrReq               0
ns3:FrstTradDt            0
ns3:TermntnDt             0
ns3:RlvntCmptntAuthrty    0
ns3:RlvntTradgVn          0
ns3:FrDt                  0
ns3:ToDt                  0
ns3:OptnTp                0
Ccy5                      0
ns3:OptnExrcStyle         0
ns3:DlvryTp               0
ns3:ISIN40                0
ns3:XpryDt                0
dtype: int64

In [53]:
data_set.shape

(141822, 30)

In [61]:
cate_features = [feature for feature in data_set.columns if data_set[feature].dtype == "O"]
len(cate_features)

28

In [74]:
for feature in cate_features:
    labels_ordered = data_set.groupby(feature)[numerical_features[0]].median().sort_values().index
    labels_ordered = {k:i for i, k in enumerate(labels_ordered, 0)}
    data_set[feature] = data_set[feature].map(labels_ordered)

In [75]:
data_set.head(10)

,ns2:Id = ns3:NtlCmptntAuthrty,ns2:Id2,ns2:BizMsgIdr,ns2:MsgDefIdr,ns2:CreDt,ns3:NtlCmptntAuthrty,ns3:Dt,ns3:Id,ns3:FullNm,ns3:ShrtNm,ns3:ClssfctnTp,ns3:NtnlCcy,ns3:CmmdtyDerivInd,ns3:Issr,ns3:Id3,ns3:IssrReq,ns3:FrstTradDt,ns3:TermntnDt,ns3:RlvntCmptntAuthrty,ns3:RlvntTradgVn,ns3:FrDt,ns3:ToDt,ns3:PricMltplr,ns3:OptnTp,ns3:Amt,Ccy5,ns3:OptnExrcStyle,ns3:DlvryTp,ns3:ISIN40,ns3:XpryDt
0,0,0,0,0,0,0,0,68707,74228,33488,179,36,0,179,125,0,4558,125,17,74,373,1,100.0,2,52.0,8,3,1,1534,62
1,0,0,0,0,0,0,0,68707,75034,33488,179,36,0,179,64,0,4560,144,17,74,373,1,100.0,2,52.0,8,3,1,1534,62
2,0,0,0,0,0,0,0,68707,74245,33488,179,36,0,179,97,0,4556,148,17,74,373,1,100.0,2,52.0,8,3,1,1534,62
3,0,0,0,0,0,0,0,68707,74245,33488,179,36,0,179,95,0,4557,117,17,74,373,1,100.0,2,52.0,8,3,1,1534,62
4,0,0,0,0,0,0,0,68706,66999,31484,263,36,0,117,132,1,4506,152,17,97,373,1,100.0,2,52.0,8,3,1,1534,62
5,0,0,0,0,0,0,0,68706,66999,31484,263,36,0,117,2,0,4505,18,17,97,373,1,100.0,2,52.0,8,3,1,1534,62
6,0,0,0,0,0,0,0,68706,70582,31484,263,36,0,117,172,0,2043,105,17,97,373,1,100.0,2,52.0,8,3,1,1534,62
7,0,0,0,0,0,0,0,68705,23919,22536,319,36,0,171,40,0,3409,40,17,74,401,0,100.0,2,52.0,8,3,1,1534,62
8,0,0,0,0,0,0,0,68705,23919,22536,319,36,0,171,39,0,3396,40,17,74,401,0,100.0,2,52.0,8,3,1,1534,62
9,0,0,0,0,0,0,0,68705,23921,22536,319,36,0,171,173,0,4835,65,17,74,62,0,100.0,2,52.0,8,3,1,1534,62

In [79]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 6)
pca.fit(data_set)
data_set = pd.DataFrame(pca.transform(data_set))
data_set.columns = ["FinInstrmGnlAttrbts.Id", "FinInstrmGnlAttrbts.FullNm", "FinInstrmGnlAttrbts.ClssfctnTp", "FinInstrmGnlAttrbts.CmmdtyDerivInd", "FinInstrmGnlAttrbts.NtnlCcy", "Issr"]
data_set.head(10)

,FinInstrmGnlAttrbts.Id,FinInstrmGnlAttrbts.FullNm,FinInstrmGnlAttrbts.ClssfctnTp,FinInstrmGnlAttrbts.CmmdtyDerivInd,FinInstrmGnlAttrbts.NtnlCcy,Issr
0,39590.767208,16571.224602,-17202.094730,-629.643108,-778.071269,125.685989
1,40090.475341,17182.701528,-17362.446338,-639.054828,-793.466686,125.223951
2,39601.288418,16584.200375,-17205.477402,-629.874939,-775.949515,125.462024
3,39601.282972,16584.202267,-17205.461415,-629.874009,-776.341635,125.776525
4,34146.838945,11420.973954,-17489.922969,-562.926777,-611.227389,131.301552
5,34146.722100,11421.315370,-17489.807596,-563.056790,-603.946775,132.696962
6,36341.213718,14223.188955,-18191.597932,-653.475941,1769.638203,344.721418
7,3134.810178,-19742.214293,-16624.307413,-155.113219,1213.164744,229.875652
8,3134.667602,-19741.770236,-16624.248719,-155.369617,1226.113970,230.990606
9,3151.398598,-19789.200991,-16631.151650,-127.368023,-199.343963,107.703969

In [80]:
data_set.shape

(141822, 6)

In [81]:
data_set.to_csv("result.csv", header = False, index = False)